spring:
  application:
    name: Users-MS
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/myProject # mysql configuration
    username: CapstoneUser
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect    
      
#eureka client configuration
server:
  port: ${PORT:0}     #0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost # configuration for automatic mapping
    prefer-ip-address: true # configuration for automatic mapping
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  

    

