spring:
  application:
    name: Eureka_Discovery_Server
    
#configuration for eureka server 

server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost      
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  
      